apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf
data:
  env: |
    MONGO_DSN=mongodb://root:root@mongodb/nest?authSource=admin
    KAFKA_CLIENT_ID=code-delivery
    KAFKA_BROKER=pkc-6ojv2.us-west4.gcp.confluent.cloud:9092
    KAFKA_CONSUMER_GROUP_ID=code-delivery
    KAFKA_SASL_USERNAME=VG2RMN6NPZFUGNOG
    KAFKA_SASL_PASSWORD=XjS5REYU6AUnhkcC9c/xsz1Fc8k1jwxy1lqwdOKA+kw9C8RxbvAra0B4SsVEMtP7