apiVersion: v1
kind: ConfigMap
metadata:
  name: simulator-conf
data:
  env: |
    KafkaReadTopic=route.new-direction
    KafkaProduceTopic=route.new-position
    KafkaBootstrapServers=pkc-419q3.us-east4.gcp.confluent.cloud:9092
    KafkaConsumerGroupId=simulator
    security.protocol="SASL_SSL"
    sasl.mechanisms="PLAIN"
    sasl.username="NQIRQZ7QRLV4FN7J"
    sasl.password="S91yyyl5cisbZ1pIcljPkuwhdrTwbOdcFumgkT51YdJC4woXHXNIWH5XXXffiLmn"
